# Site title
title = "studiomettā"
base_url = "https://musical-paprenjak-d5b9df.netlify.app"
#"https://musical-paprenjak-d5b9df.netlify.app"#"https://studiometta.in"
description = "Studio Metta Architecture and Design"
compile_sass = true
theme = "andromeda"


[extra]
header_links = [
    {name = "Instagram", url = "https://www.instagram.com/studiometta/"}
]
# license = "CC BY-NC 2.0"
# email = "yogeshkurhade@gmail.com"
# name = "Studio Metta"
# favicon = "/images/favicon.ico"
